var gamedata = [
    {
        "gametype": 4,
        "aid": 11,
        "gameName": "诛仙3",
        "shortName": "zx",
        "pyName": "zhuxian",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 1,
        "isNew": 0
    },
    {
        "gametype": 3,
        "aid": 10,
        "gameName": "鑫仔国际2",
        "shortName": "wmgj",
        "pyName": "wanmeiguoji",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 1,
        "isNew": 0
    },
    {
        "gametype": 21,
        "aid": 23,
        "gameName": "笑傲江湖OL",
        "shortName": "xajh",
        "pyName": "xiaoaojianghu",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 1,
        "isNew": 0
    },
    {
        "gametype": 9,
        "aid": 15,
        "gameName": "梦幻诛仙2",
        "shortName": "mhzx2",
        "pyName": "menghuanzhuxian2",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 0,
        "isNew": 0
    },
    {
        "gametype": 2,
        "aid": 9,
        "gameName": "武林外传",
        "shortName": "wlwc",
        "pyName": "wulinwaichuan",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 0,
        "isNew": 0
    },
    {
        "gametype": 8,
        "aid": 18,
        "gameName": "神鬼传奇",
        "shortName": "sgcq",
        "pyName": "shenguichuanqi",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 0,
        "isNew": 0
    },
    {
        "gametype": 12,
        "aid": 25,
        "gameName": "神鬼世界",
        "shortName": "sgsj",
        "pyName": "shenguishijie",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 0,
        "isNew": 0
    },
    {
        "gametype": 1,
        "aid": 1,
        "gameName": "鑫仔世界",
        "shortName": "wmsj",
        "pyName": "wanmeishijie",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 0,
        "isNew": 0
    },
    {
        "gametype": 5,
        "aid": 12,
        "gameName": "赤壁",
        "shortName": "cb",
        "pyName": "chibi",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 0,
        "isNew": 0
    },
    {
        "gametype": 6,
        "aid": 13,
        "gameName": "热舞派对Ⅱ",
        "shortName": "rwpd",
        "pyName": "rewupaidui",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 0,
        "isNew": 0
    },
    {
        "gametype": 11,
        "aid": 19,
        "gameName": "神魔大陆2",
        "shortName": "smdl",
        "pyName": "shenmodalu",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 0,
        "isNew": 0
    },
    {
        "gametype": 7,
        "aid": 14,
        "gameName": "口袋西游",
        "shortName": "kdxy",
        "pyName": "koudaixiyou",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 0,
        "isNew": 0
    },
    {
        "gametype": 15,
        "aid": 26,
        "gameName": "神雕侠侣",
        "shortName": "sdxl",
        "pyName": "shendiaoxialv",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 0,
        "isNew": 0
    },
    {
        "gametype": 19,
        "aid": 28,
        "gameName": "圣斗士星矢OL",
        "shortName": "sdsx",
        "pyName": "shengdoushixing",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 0,
        "isNew": 0
    },
    {
        "gametype": 22,
        "aid": 9999,
        "gameName": "DOTA2",
        "shortName": "dota",
        "pyName": "dota",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 1,
        "isNew": 0
    },
    {
        "gametype": 37,
        "aid": 52,
        "gameName": "神鬼传奇经典版",
        "shortName": "sgcqjdb",
        "pyName": "shenguichuanqijingdianban",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 0,
        "isNew": 0
    },
    {
        "gametype": 36,
        "aid": 200001,
        "gameName": "HEX",
        "shortName": "hex",
        "pyName": "hex",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 0,
        "isNew": 0
    },
    {
        "gametype": 34,
        "aid": 46,
        "gameName": "蜀山缥缈录",
        "shortName": "sspml",
        "pyName": "shushanpiaomiaolu",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 0,
        "isNew": 0
    },
    {
        "gametype": 48,
        "aid": 200011,
        "gameName": "幻影突击",
        "shortName": "hytj",
        "pyName": "huanyingtuji",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 0,
        "isNew": 0
    },
    {
        "gametype": 50,
        "aid": 200013,
        "gameName": "创世战车",
        "shortName": "cszc",
        "pyName": "chuangshizhanche",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 0,
        "isNew": 1
    },
    {
        "gametype": 52,
        "aid": 200015,
        "gameName": "CS:GO",
        "shortName": "CS:GO",
        "pyName": "csgo",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 1,
        "isNew": 1
    },
    {
        "gametype": 20,
        "aid": 36,
        "gameName": "TOUCH",
        "shortName": "touch",
        "pyName": "touch",
        "status": 1,
        "sortIndex": null,
        "type": 3,
        "isHot": 0,
        "isNew": 0
    },
    {
        "gametype": 69,
        "aid": 54,
        "gameName": "怀旧版神雕侠侣",
        "shortName": "sdly",
        "pyName": "sdly",
        "status": 1,
        "sortIndex": null,
        "type": 1,
        "isHot": 0,
        "isNew": 0
    }
]